'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''lblApiKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApiKey As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtApiKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApiKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rqAPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqAPI As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblPagerSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagerSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtPagerSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPagerSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPageSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeatDirection As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRepeatDirection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRepeatLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeatLayout As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlRepeatLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRepeatLayout As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColumns As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumns As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImageWidth As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImageWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWidth As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPadding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPadding As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtPadding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPadding As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSpacing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpacing As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtSpacing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpacing As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblListStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListStyle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtListStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtListStyle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblListItemStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListItemStyle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtListItemStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtListItemStyle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblListItemAltStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListItemAltStyle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtListItemAltStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtListItemAltStyle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPTheme As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlPPTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPTheme As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblPPOpacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPOpacity As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtPPOpacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPOpacity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPPVideoSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPVideoSize As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlPPVideoSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPVideoSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblPPShowSuggestedVideos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPShowSuggestedVideos As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkSuggestedVideos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSuggestedVideos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPPPlayerControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPPlayerControls As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkPlayerControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPlayerControls As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPPShowTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPShowTitle As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkShowTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowTitle As Global.System.Web.UI.WebControls.CheckBox
End Class
